[package]
name = "airagi-bin"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The Air Artificial General Intelligence"
homepage = "https://github.com/LambdaAlpha/airagi-doc"
repository = "https://github.com/LambdaAlpha/airagi"
keywords = ["air", "ai", "agi", "solver", "logic"]
categories = ["science"]

[dependencies.airagi]
path = "../lib"
version = "0.0.1"
